### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by DomoApp** [kisi-inc/kisi-ios-st2u-framework#11]
Hello guys, 

I am about to start implementing the SDK on both iOS and Android using react native, since there is currently no SDK for React Native it is necessary to create a bridge, my question is if you plan to create the SDK for React Native since it also I have seen other people doing the same https://github.com/kisi-inc/kisi-android-st2u-sdk-public/issues/1 it would be very helpful to the entire community

Regards.

**Comment by mikaoj** [comment]
No such plans at the moment.
But I believe some other users have done it.

**Comment by greena25** [comment]
> No such plans at the moment. But I believe some other users have done it.

Anything that you can share? 

It seems like this is something that should be a priority. I would think that providing support for a dev community like react native and expo would be a good way to kickstart interest in Kisi and inspire ideas among developers that otherwise may not come to be. You guys have built a great API and dx, show the react native community how to use Kisi and I have a hard time believing it wouldn't drum up some business.

I'm currently running multiple fully autonomous brick and mortar stores with Kisi APIs. It would be cool to see what other people could come up with.

**Comment by ce07c3** [comment]
We'd love to do it, we just don't have any React Native experience as we're 100% "metal". I wonder how difficult it would be.

**Comment by ce07c3** [comment]
It's likely a very different story due to Bluetooth and NFC. If you figure it out, happy to review – we checked and we won't have the capacity to pull this off. It would need to be thoroughly tested as well.

**Comment by DomoApp** [comment]
I have already made the bridge and we have implemented tap to unlock in our app, but it would definitely be extra points for you if you made an official bridge/SDK for the community, my contribution here is to confirm that it can be done and it works well 💪😃

**Comment by pnogier** [comment]
Hi there ! 
Just a quick message to confirm that I was also able to build a bridge for our RN app to enable the Tap to Unlock feature so I can confirm it is doable, but would definitely be better to have an official wrapper as RN is now quickly growing, pushed by Expo. 

We built the wrapper simply with NativeModules, but expo also offers the ability to build expo-modules to be used very easily in any Expo app as mentioned by @greena25. Also giving this tutorial link as example: https://docs.expo.dev/modules/third-party-library/
